config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("", include("senders.urls")),
    path("", include("authorizations.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )

senders/urls.py
from django.urls import path

from senders.views import (
    MailAttemptListView,
    MailingCreateView,
    MailingDeleteView,
    MailingListView,
    MailingSendView,
    MailingStatisticView,
    MailingUpdateView,
    MessageCreateView,
    MessageDeleteView,
    MessageListView,
    MessageUpdateView,
    RecipientCreateView,
    RecipientDeleteView,
    RecipientListView,
    RecipientUpdateView,
)

app_name = "senders"

urlpatterns = [
    path(
        "statistics/",
        MailingStatisticView.as_view(),
        name="statistics",
    ),
    path(
        "recipients/",
        RecipientListView.as_view(),
        name="recipient_list",
    ),
    path(
        "recipient/add/",
        RecipientCreateView.as_view(),
        name="recipient_create",
    ),
    path(
        "recipient/edit/<int:pk>/",
        RecipientUpdateView.as_view(),
        name="recipient_edit",
    ),
    path(
        "recipient/delete/<int:pk>/",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path(
        "messages/",
        MessageListView.as_view(),
        name="message_list",
    ),
    path(
        "message/add/",
        MessageCreateView.as_view(),
        name="message_create",
    ),
    path(
        "message/edit/<int:pk>/",
        MessageUpdateView.as_view(),
        name="message_edit",
    ),
    path(
        "message/delete/<int:pk>/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path(
        "mailings/",
        MailingListView.as_view(),
        name="mailing_list",
    ),
    path(
        "mailing/add/",
        MailingCreateView.as_view(),
        name="mailing_create",
    ),
    path(
        "mailing/edit/<int:pk>/",
        MailingUpdateView.as_view(),
        name="mailing_edit",
    ),
    path(
        "mailing/delete/<int:pk>/",
        MailingDeleteView.as_view(),
        name="mailing_delete",
    ),
    path(
        "mail_attempts/",
        MailAttemptListView.as_view(),
        name="mail_attempt_list",
    ),
    path(
        "mailing/send/<int:pk>/",
        MailingSendView.as_view(),
        name="mailing_send",
    ),
]

senders/models.py
from django.db import models

from senders.constants import (
    MAIL_SEND_STATUS,
    MAILING_STATUS,
    NAME_LEN,
    SUBJECT_LEN,
)
from users.models import CustomUser


class Recipient(models.Model):
    email = models.EmailField(
        "E-mail",
        unique=True,
    )
    first_name = models.CharField(
        "Имя",
        max_length=NAME_LEN,
    )
    last_name = models.CharField(
        "Фамилия",
        max_length=NAME_LEN,
    )
    middle_name = models.CharField(
        "Отчество",
        max_length=NAME_LEN,
        blank=True,
    )
    comment = models.TextField(
        "Комментарий",
        null=True,
        blank=True,
    )
    owner = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        related_name="recipients",
    )

    class Meta:
        verbose_name = "Получатель рассылки"
        verbose_name_plural = "Получатели рассылки"
        ordering = ("first_name", "last_name")
        permissions = [
            ("can_edit_recipient", "Можнет редактировать получателя"),
            ("can_delete_recipient", "Может удалить получателя"),
        ]

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


class Message(models.Model):
    subject = models.CharField(
        "Тема",
        max_length=SUBJECT_LEN,
    )
    body = models.TextField(
        "Текст",
    )
    owner = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        related_name="messages",
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ("subject",)
        permissions = [
            ("can_edit_message", "Может редактировать сообщение"),
            ("can_delete_message", "Может удалить сообщение"),
        ]

    def __str__(self) -> str:
        return str(self.subject)


class Mailing(models.Model):
    start_date = models.DateTimeField(
        "Время отправки",
        null=True,
    )
    end_date = models.DateTimeField(
        "Время окончания",
        null=True,
    )
    status = models.CharField(
        "Статус",
        choices=tuple(MAILING_STATUS.items()),
        default="created",
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        related_name="mailings",
        verbose_name="Сообщение",
    )
    recipients = models.ManyToManyField(
        Recipient,
        related_name="mailings",
        verbose_name="Получатели",
    )
    owner = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        related_name="mailings",
    )
    success_count = models.IntegerField("Успешно", default=0)
    failure_count = models.IntegerField("Не успешно", default=0)

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = (
            "-start_date",
            "-end_date",
            "status",
        )
        permissions = [
            (
                "can_manage_own_mailings",
                "Может управлять собственными рассылками",
            ),
            ("can_manage_all_mailings", "Может управлять всеми рассылками"),
        ]

    def get_mail_attempts(self):
        return MailAttemptToSend.objects.filter(mailing=self)

    def update_statistics(self):
        attempts = self.get_mail_attempts()
        self.success_count = attempts.filter(
            status=MAIL_SEND_STATUS["success"],
        ).count()
        self.failure_count = attempts.filter(
            status=MAIL_SEND_STATUS["failure"],
        ).count()
        self.save()

    def __str__(self) -> str:
        return f"{self.start_date} - {self.end_date} | [{self.status}]"


class MailAttemptToSend(models.Model):
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        related_name="attempts",
        verbose_name="Рассылка",
    )
    attempt_date = models.DateTimeField(
        "Дата и время",
        auto_now_add=True,
    )
    status = models.CharField(
        "Статус",
        choices=tuple(MAIL_SEND_STATUS.items()),
    )
    server_response = models.TextField(
        "Ответ почтового сервера",
        default="Успешно",
    )

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"
        ordering = ("-attempt_date", "status")

    def __str__(self) -> str:
        return f"{self.mailing.owner.first_name} [{self.status}]"

senders/forms.py
from django import forms

from senders.models import Mailing, Message, Recipient


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        default_class = "form-control"

        for field in self.fields.values():
            field.widget.attrs["class"] = (
                f"{field.widget.attrs.get('class', '')} {default_class}"
            )


class RecipientForm(BaseForm):
    class Meta:
        model = Recipient
        fields = (
            "email",
            "first_name",
            "last_name",
            "middle_name",
            "comment",
        )
        widgets = {
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "middle_name": forms.TextInput(attrs={"class": "form-control"}),
            "comment": forms.Textarea(attrs={"class": "form-control"}),
        }


class MessageForm(BaseForm):
    class Meta:
        model = Message
        fields = ("subject", "body")
        widgets = {
            "subject": forms.TextInput(attrs={"class": "form-control"}),
            "body": forms.Textarea(attrs={"class": "form-control"}),
        }


class MailingForm(BaseForm):
    class Meta:
        model = Mailing
        fields = (
            "start_date",
            "end_date",
            "status",
            "message",
            "recipients",
        )
        widgets = {
            "start_date": forms.DateTimeInput(
                attrs={"class": "form-control", "type": "datetime-local"}
            ),
            "end_date": forms.DateTimeInput(
                attrs={"class": "form-control", "type": "datetime-local"}
            ),
            "status": forms.Select(attrs={"class": "form-control"}),
            "message": forms.Select(attrs={"class": "form-control"}),
            "recipients": forms.CheckboxSelectMultiple(
                attrs={"class": "form-check"}
            ),
        }

senders/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count, Q
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from senders.forms import MailingForm, MessageForm, RecipientForm
from senders.models import MailAttemptToSend, Mailing, Message, Recipient
from senders.tasks import send_mailing


class RecipientListView(LoginRequiredMixin, ListView):
    model = Recipient
    context_object_name = "recipients"

    def get_queryset(self):
        return Recipient.objects.filter(owner=self.request.user)


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("senders:recipient_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("senders:recipient_list")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.owner != self.request.user:
            raise Http404("У Вас недостаточно прав для этой операции")
        return obj


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    success_url = reverse_lazy("senders:recipient_list")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.owner != self.request.user:
            raise Http404("У Вас недостаточно прав для этой операции")
        return obj


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    context_object_name = "messages"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("senders:message_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("senders:message_list")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.owner != self.request.user:
            raise Http404("У Вас недостаточно прав для этой операции")
        return obj


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy("senders:message_list")

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.owner != self.request.user:
            raise Http404("У Вас недостаточно прав для этой операции")
        return obj


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    context_object_name = "mailings"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff or self.request.user.has_perm(
            "senders.can_manage_all_mailings"
        ):
            return queryset
        return queryset.filter(owner=self.request.user)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("senders:mailing_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("senders:mailing_list")

    def get_object(self, queryset=None):
        mailing = super().get_object(queryset)
        if mailing.owner != self.request.user:
            raise Http404(
                "Вы не можете редактировать чужую рассылку",
            )
        return mailing

    def form_invalid(self, form):
        messages.error(
            self.request,
            "Произошла ошибка при сохранении рассылки",
        )
        return super().form_invalid(form)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy("senders:mailing_list")

    def get_object(self, queryset=None):
        mailing = super().get_object(queryset)
        if mailing.owner != self.request.user:
            raise Http404("Вы не можете удалить чужую рассылку")
        return mailing

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "Рассылка успешно удалена")
        return super().delete(request, *args, **kwargs)


class MailAttemptListView(LoginRequiredMixin, ListView):
    model = MailAttemptToSend
    context_object_name = "attempts"


class ManagerOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class MailingStatisticView(ManagerOnlyMixin, ListView):
    model = Mailing
    template_name = "senders/statistics.html"
    context_object_name = "mailings"

    def get_queryset(self):
        return (
            Mailing.objects.values("status")
            .annotate(
                total_success_count=Count(
                    "attempts",
                    filter=Q(attempts__status="success"),
                ),
                total_failure_count=Count(
                    "attempts",
                    filter=Q(attempts__status="failure"),
                ),
            )
            .order_by("status")
        )


class MailingSendView(LoginRequiredMixin, View):
    def get(self, request, pk):
        try:
            mailing = Mailing.objects.get(pk=pk, owner=request.user)
            send_mailing(mailing)
            messages.success(request, "Рассылка отправлена!")
        except Mailing.DoesNotExist:
            messages.error(request, "Вы не можете отправить эту рассылку")
        return HttpResponseRedirect(reverse("senders:mailing_list"))

templates/senders/mailattempttosend_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h2 class="mt-3 mb-3">Список попыток рассылки</h2>
  {% if attempts %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Время попытки</th>
          <th>Статус</th>
          <th>Ответ сервера</th>
          <th>Рассылка</th>
        </tr>
      </thead>
      <tbody>
        {% for attempt in attempts %}
          <tr>
            <td>{{ attempt.attempt_date }}</td>
            <td>{{ attempt.get_status_display }}</td>
            <td>
              {% if attempt.status == "success" %}
                <span>Успех</span>
              {% else %}
                <span>Отказ</span>
              {% endif %}
            </td>
            <td>{{ attempt.mailing.message.subject }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Нет данных для отображения.</p>
  {% endif %}
{% endblock %}

templates/senders/mailing_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Удалить рассылку{% endblock %}
{% block content %}
  <h2>Вы уверены, что хотите удалить рассылку?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'senders:mailing_list' %}" class="btn btn-secondary">Отменить</a>
  </form>
{% endblock %}

templates/senders/mailing_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}{{ view.title }}{% endblock %}
{% block content %}
  <h2>
    {% if mailing %}
      Редактировать рассылку
    {% else %}
      Добавить рассылку
    {% endif %}
  </h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
      {% if mailing %}
        Сохранить
      {% else %}
        Добавить
      {% endif %}
    </button>
  </form>
{% endblock %}

templates/senders/mailing_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Список рассылок{% endblock %}
{% block content %}
  <h2 class="mt-3 mb-3">
    Список рассылок
    <a href="{% url 'senders:mailing_create' %}" class="btn btn-primary">+</a>
  </h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Время отправки</th>
        <th>Время окончания</th>
        <th>Статус</th>
        <th>Сообщение</th>
        <th>Получатели</th>
        {% if mailing.owner == user %}<th>Действия</th>{% endif %}
      </tr>
    </thead>
    <tbody>
      {% for mailing in mailings %}
        <tr>
          <td>{{ mailing.start_date }}</td>
          <td>{{ mailing.end_date }}</td>
          <td>{{ mailing.get_status_display }}</td>
          <td>{{ mailing.message.body|truncatewords:5 }}</td>
          <td>{{ mailing.recipients.count }}</td>
          {% if request.user == mailing.owner %}
            <td>
              <a href="{% url 'senders:mailing_edit' mailing.id %}"
                 class="btn btn-warning btn-sm">Редактировать</a>
              <a href="{% url 'senders:mailing_delete' mailing.id %}"
                 class="btn btn-danger btn-sm">Удалить</a>
            </td>
          <td>
            <a href="{% url 'senders:mailing_send' mailing.id %}" class="btn btn-success btn-sm">Отправить</a>
          </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/senders/message_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Удалить сообщение{% endblock %}
{% block content %}
  <h2>Вы уверены, что хотите удалить сообщение "{{ message.subject }}"?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'senders:message_list' %}" class="btn btn-secondary">Отменить</a>
  </form>
{% endblock %}

templates/senders/message_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Добавить/Редактировать сообщение{% endblock %}
{% block content %}
  <h2>
    {% if message %}
      Редактировать
    {% else %}
      Добавить
    {% endif %}
    сообщение
  </h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
      {% if message %}
        Сохранить
      {% else %}
        Добавить
      {% endif %}
    </button>
  </form>
{% endblock %}

templates/senders/message_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Список сообщений{% endblock %}
{% block content %}
  <h2 class="mt-3 mb-3">
    Список сообщений
    <a href="{% url 'senders:message_create' %}" class="btn btn-primary">+</a>
  </h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Тема</th>
        <th>Текст</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for message in messages %}
        <tr>
          <td>{{ message.subject }}</td>
          <td>{{ message.body|truncatewords:10 }}</td>
          <td>
            {% if request.user == message.owner %}
            <a href="{% url 'senders:message_edit' message.id %}"
               class="btn btn-warning btn-sm">Редактировать</a>
            <a href="{% url 'senders:message_delete' message.id %}"
               class="btn btn-danger btn-sm">Удалить</a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/senders/recipient_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Удалить получателя{% endblock %}
{% block content %}
  <h2>Вы уверены, что хотите удалить получателя {{ recipient.name }}?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'senders:recipient_list' %}" class="btn btn-secondary">Отменить</a>
  </form>
{% endblock %}

templates/senders/recipient_form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Добавить/Редактировать получателя{% endblock %}
{% block content %}
  <h2>
    {% if recipient %}
      Редактировать
    {% else %}
      Добавить
    {% endif %}
    получателя
  </h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
      {% if recipient %}
        Сохранить
      {% else %}
        Добавить
      {% endif %}
    </button>
  </form>
{% endblock %}

templates/senders/recipient_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Список получателей{% endblock %}
{% block content %}
  <h2 class="mt-3 mb-3">
    Список получателей
    <a href="{% url 'senders:recipient_create' %}" class="btn btn-primary">+</a>
  </h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Ф.И.О</th>
        <th>Комментарий</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      {% for recipient in recipients %}
        <tr>
          <td>{{ recipient.email }}</td>
          <td>{{ recipient.last_name }} {{ recipient.first_name }} {{ recipient.middle_name }}</td>
          <td>{{ recipient.comment|truncatewords:5 }}</td>
          <td>
            {% if request.user == recipient.owner %}
            <a href="{% url 'senders:recipient_edit' recipient.id %}"
               class="btn btn-warning btn-sm">Редактировать</a>
            <a href="{% url 'senders:recipient_delete' recipient.id %}"
               class="btn btn-danger btn-sm">Удалить</a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/senders/statistics.html
{% extends 'base.html' %}
{% load set_mailing_status %}
{% block content %}
  <h2 class="mt-3 mb-3">Статистика рассылок</h2>
  <table class="table mt-4">
    <thead>
      <tr>
        <th>Статус</th>
        <th>Успешные попытки</th>
        <th>Неуспешные попытки</th>
      </tr>
    </thead>
    <tbody>
      {% for mailing in mailings %}
        <tr>
          <td>{{ mailing.status|status_display }}</td>
          <td>{{ mailing.total_success_count }}</td>
          <td>{{ mailing.total_failure_count }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="text-center">
    <img src="https://img.freepik.com/free-vector/data-analysis-concept-illustration_114360-8073.jpg"
         alt="mail"
         class="img-fluid">
  </div>
{% endblock %}