authorizations/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from authorizations.views import RegisterView

app_name = "authorizations"

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("", include("senders.urls")),
    path("", include("authorizations.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )

senders/urls.py
from django.urls import path

from senders.views import (
    MailAttemptListView,
    MailingCreateView,
    MailingDeleteView,
    MailingListView,
    MailingSendView,
    MailingStatisticView,
    MailingUpdateView,
    MessageCreateView,
    MessageDeleteView,
    MessageListView,
    MessageUpdateView,
    RecipientCreateView,
    RecipientDeleteView,
    RecipientListView,
    RecipientUpdateView,
)

app_name = "senders"

urlpatterns = [
    path(
        "statistics/",
        MailingStatisticView.as_view(),
        name="statistics",
    ),
    path(
        "recipients/",
        RecipientListView.as_view(),
        name="recipient_list",
    ),
    path(
        "recipient/add/",
        RecipientCreateView.as_view(),
        name="recipient_create",
    ),
    path(
        "recipient/edit/<int:pk>/",
        RecipientUpdateView.as_view(),
        name="recipient_edit",
    ),
    path(
        "recipient/delete/<int:pk>/",
        RecipientDeleteView.as_view(),
        name="recipient_delete",
    ),
    path(
        "messages/",
        MessageListView.as_view(),
        name="message_list",
    ),
    path(
        "message/add/",
        MessageCreateView.as_view(),
        name="message_create",
    ),
    path(
        "message/edit/<int:pk>/",
        MessageUpdateView.as_view(),
        name="message_edit",
    ),
    path(
        "message/delete/<int:pk>/",
        MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path(
        "mailings/",
        MailingListView.as_view(),
        name="mailing_list",
    ),
    path(
        "mailing/add/",
        MailingCreateView.as_view(),
        name="mailing_create",
    ),
    path(
        "mailing/edit/<int:pk>/",
        MailingUpdateView.as_view(),
        name="mailing_edit",
    ),
    path(
        "mailing/delete/<int:pk>/",
        MailingDeleteView.as_view(),
        name="mailing_delete",
    ),
    path(
        "mail_attempts/",
        MailAttemptListView.as_view(),
        name="mail_attempt_list",
    ),
    path(
        "mailing/send/<int:pk>/",
        MailingSendView.as_view(),
        name="mailing_send",
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}Управление рассылками{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet" />
  </head>
  <body>
    <div class="container mt-4">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand fw-bold" href="/">ПисьмоX</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'senders:recipient_list' %}">Получатели</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'senders:message_list' %}">Сообщения</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'senders:mailing_list' %}">Рассылки</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'senders:mail_attempt_list' %}">Попытки отправки</a>
            </li>
            {% if user.is_authenticated %}
              {% if user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'senders:statistics' %}">Статистика</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'authorizations:logout' %}">Выход</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'authorizations:login' %}">Вход</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Главная страница{% endblock %}
{% block content %}
  <h1 class="mb-4 mt-3">
    Добро пожаловать,
    {% if user.first_name %}
      {{ user.first_name }}
    {% else %}
      {{ user.username }}
    {% endif %}
    !
  </h1>
  <div class="row">
    <div class="col-md-4">
      <h4>Общее количество рассылок</h4>
      <p>{{ total_mailings }}</p>
    </div>
    <div class="col-md-4">
      <h4>Активные рассылки</h4>
      <p>{{ active_mailings }}</p>
    </div>
    <div class="col-md-4">
      <h4>Уникальные получатели</h4>
      <p>{{ unique_recipients }}</p>
    </div>
    <div class="text-center">
      <img src="https://img.freepik.com/free-vector/envelope-concept-illustration_114360-1353.jpg"
           alt="mail"
           class="img-fluid">
    </div>
  </div>
{% endblock %}